### PR TITLE
fixed preview extension

### LINKED ISSUE #42: fix preview extension
## Reference(s) (Optional)
https://swiswiswift.com/2022-01-03/

### PR DESCRIPTION
**Pull request by naoki-mrmt**
## Issue

- close #42 

## Reference(s) (Optional)
- https://www.apollomaniacs.com/ipod/ifamily_screensize.htm

### CODE REVIEW

File: VolleyballScoreApp/Extension/PreviewProviderExtension.swift [hunk 1]
```diff
@@ -8,19 +8,19 @@
...
 
 extension View {
-    /// iPad Pro 11inch用のprevセッティング
-    func iPadPro11() -> some View {
+    /// ppi326のprevセッティング
+    func ppi326() -> some View {
         self
-            .previewDisplayName("iPad Pro (11-inch)")
-            .previewDevice("iPad Pro (12.9-inch) (6th generation)")
+            .previewDevice(PreviewDevice(rawValue: "iPad mini (5th generation)"))
```
Comment (oimo-rev) [inline VolleyballScoreApp/Extension/PreviewProviderExtension.swift]: 6thじゃなかったっけ？

Comment (naoki-mrmt) [reply VolleyballScoreApp/Extension/PreviewProviderExtension.swift]: こちらで修正しました
[8f047d2](https://github.com/naoki-mrmt/VolleyballScoreApp/pull/43/commits/8f047d23952a554cb85655197e8c6b45ee9955ef)

**Review by oimo-rev — APPROVED** [review]
LGTM
